#ifndef CNC_HAL_RESET_H
#define CNC_HAL_RESET_H
#ifdef __cplusplus
extern "C"
{
#endif

#undef ENABLE_COOLANT
#undef ENABLE_SKEW_COMPENSATION
#undef SKEW_COMPENSATION_XY_ONLY
#undef ENABLE_LINACT_PLANNER
#undef ENABLE_LINACT_COLD_START
#undef ENABLE_BACKLASH_COMPENSATION
#undef S_CURVE_ACCELERATION_LEVEL
#undef BRESENHAM_16BIT
#undef ENABLE_EXTRA_SYSTEM_CMDS
#undef RAM_ONLY_SETTINGS
#undef FORCE_SOFT_POLLING
#undef STATUS_AUTOMATIC_REPORT_INTERVAL_ENABLE
#undef DISABLE_ALL_CONTROLS
#undef ESTOP_PULLUP_ENABLE
#undef SAFETY_DOOR_PULLUP_ENABLE
#undef FHOLD_PULLUP_ENABLE
#undef CS_RES_PULLUP_ENABLE
#undef DISABLE_ALL_LIMITS
#undef LIMIT_X_DISABLE
#undef LIMIT_Y_DISABLE
#undef LIMIT_Z_DISABLE
#undef LIMIT_X2_DISABLE
#undef LIMIT_Y2_DISABLE
#undef LIMIT_Z2_DISABLE
#undef LIMIT_X_PULLUP_ENABLE
#undef LIMIT_Y_PULLUP_ENABLE
#undef LIMIT_Z_PULLUP_ENABLE
#undef LIMIT_X2_PULLUP_ENABLE
#undef LIMIT_Y2_PULLUP_ENABLE
#undef LIMIT_Z2_PULLUP_ENABLE
#undef DISABLE_PROBE
#undef PROBE_PULLUP_ENABLE
#undef ENABLE_MULTI_STEPPER_AXIS
#undef TOOL1
#undef TOOL2
#undef SPINDLE_PWM
#undef SPINDLE_PWM_DIR
#undef ENABLE_LASER_PPI
#undef SOFT_SPI_ENABLED
#undef ENCODERS
#undef ENABLE_MAIN_LOOP_MODULES
#undef ENABLE_IO_MODULES
#undef ENABLE_PARSER_MODULES
#undef ENABLE_MOTION_CONTROL_MODULES
#undef ENABLE_RT_SYNC_MOTIONS
#undef DISABLE_SETTINGS_MODULES

#ifdef __cplusplus
}
#endif
#endif

